### ISSUE TITLE
Does not work with Sentry 8.0-dev

### ISSUE THREAD

**Issue by aadis** [bogdal/sentry-youtrack#10]
sentry-youtrack does not work with latest sentry off master. Since master is so so much better than 7.x, is it possible to make it work (perhaps as a separate branch) ?

Many thanks for the extension!

**Comment by bogdal** [comment]
@aadis Check [this](https://github.com/bogdal/sentry-youtrack/tree/sentry-8.x) out. Saving default field values, doesn't work yet but you should be able to create/assign issues.

**Comment by aadis** [comment]
Oh thanks! that works!
