### ISSUE TITLE
verify_ssl_certificate config value

### ISSUE THREAD

**Issue by myovchev** [bogdal/sentry-youtrack#11]
It would be nice if there is a configuration option for verifying ssl certificate, currently the youtrack client class is using a default value `verify_ssl_certificate=True`

**Comment by bogdal** [comment]
Good point :+1: `sentry-youtrack` allows to use url without valid certificate unfortunately only on the [configuration form](https://github.com/bogdal/sentry-youtrack/blob/master/sentry_youtrack/forms.py#L216).

**Comment by bogdal** [comment]
@myovchev Added in version `0.2.6`. Check [this](https://github.com/bogdal/sentry-youtrack#configuration) out.

**Comment by myovchev** [comment]
:+1:
