### ISSUE TITLE
_get_custom_project_field_details requests wrong URL

### ISSUE THREAD

**Issue by lucasvdh** [bogdal/sentry-youtrack#15]
The function **`_get_custom_project_field_details`** requests the wrong URL.

For example, this URL is requested:
`http://company.myjetbrains.com/youtrack/youtrack/rest/admin/project/PROJECT/customfield/Priority`
when the correct URL would be:
`http://company.myjetbrains.com/youtrack/rest/admin/project/PROJECT/customfield/Priority`

**Comment by bogdal** [comment]
@lucasvdh Fixed in `0.3.1`.
