### ISSUE TITLE
Make sentry sends notification emails to project members when using sentry-youtrack

### ISSUE THREAD

**Issue by swdream** [bogdal/sentry-youtrack#21]
When using sentry-youtrack plugin to create a new yt issue or assign a sentry event to an existing yt issue [1], sentry doesn't send notification emails to project members.
That is really inconvenient.
So sentry-youtrack should create a comment automatically in this case to make sentry sends notification emails.
Or is there another way to make sentry sends notification emails to project members when [1]?

Thanks & best regards.

**Comment by swdream** [comment]
@bogdal How do you think about this?

**Comment by bogdal** [comment]
@swdream In my opinion `YouTrack` should handle all notifications. Right now, assigned users to a new YT issue should be notified by default.
Assigning an existing issue doesn't bring anything new to the project, hence we shouldn't send emails in this case.

**Comment by bclermont** [comment]
instead of send a notification, why not add a comment?

**Comment by quantonganh** [comment]
> @swdream In my opinion YouTrack should handle all notifications.

I'm agree with you.

> instead of send a notification, why not add a comment?

Because we already add a link below the subject to point to the YT issue.

**Comment by swdream** [comment]
so we should close this issue. thanks
